chore: optimize ci (#2953)
* fix: basic

* fix: testing

* fix: more testing

* fix: node modules for runtime

* fix: cache next build

* fix: almost empty commit

* fix: push to mystique

* fix: setup npmrc on the ci

* fix: node version in docker

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -6,7 +6,7 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest-4-cores
-    name: 'Build'
+    name: 'build'
     strategy:
       matrix:
         env: ['test', 'production']
@@ -17,102 +17,42 @@ jobs:
             env: 'production'
           - hasTag: true
             env: 'test'
-    env:
-      APP_ENV: ${{ matrix.env }}
-    steps:
-      - uses: actions/checkout@v2
-        with:
-          # Why this? No idea ¯_(ツ)_/¯
-          # Refer - https://github.community/t/how-to-install-private-github-repository-via-npm-through-git-https-github-actions-workflow-ci/124302
-          persist-credentials: false
-      - name: Extract branch name
-        shell: bash
-        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
-        id: extract_branch
-      - uses: actions/setup-node@v3
-        with:
-          node-version: '20.17.0'
-      - name: Cache node modules
-        uses: actions/cache@v4
-        with:
-          path: |
-            ./node_modules
-          key: ${{ runner.os }}-nodejs-${{ matrix.env }}-${{ hashFiles('yarn.lock') }}
-          save-always: true
-      - name: Install Packages
-        run: |
-          git config --global url."https://${{ github.actor }}:${{ secrets.HEADOUT_CI_PACKAGE_PAT }}@github.com/".insteadOf ssh://git@github.com/
-          yarn
-      - name: Cache built NEXT
-        uses: actions/cache@v4
-        with:
-          path: |
-            ./.next/
-            ./public
-            ./.env.local
-          key: ${{ runner.os }}-nextjs-${{ matrix.env }}-${{ github.sha }}
-      - name: Prepare version label
-        run: |
-          echo "GIT_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
-      - name: Build NEXT
-        run: yarn build
-        env:
-          RELEASE_VERSION: ${{ env.GIT_VERSION }}
-          NEXT_PUBLIC_HEADOUT_DOMAIN: 'https://www.headout.com'
-
-  push-ecr:
-    name: 'CD (Deploy)'
-    needs: build
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        env: ['test', 'production']
-        hasTag:
-          - ${{ startsWith(github.ref, 'refs/tags/') }}
-        exclude:
-          - hasTag: false
-            env: 'production'
-          - hasTag: true
-            env: 'test'
-    outputs:
-      dockerImageTag: ${{ steps.docker_meta.outputs.version }}
-      ecrRegistryUrl: ${{ steps.login_ecr.outputs.registry }}
     env:
       AWS_EB_S3_BUCKET: ${{ secrets.AWS_EB_S3_BUCKET }}
       APP_ENV: ${{ matrix.env }}
       WAF_API_WHITELIST_TOKEN: ${{ secrets.WAF_API_WHITELIST_TOKEN }}
-
+    outputs:
+      dockerImageTag: ${{ steps.docker_meta.outputs.version }}
+      ecrRegistryUrl: ${{ steps.login_ecr.outputs.registry }}
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v4
+        with:
+          persist-credentials: false
+
+      - name: Validate Build Arguments
+        run: |
+          if [ -z "$APP_ENV" ] || [ -z "$WAF_API_WHITELIST_TOKEN" ]; then
+              echo "APP_ENV and/or WAF_API_WHITELIST_TOKEN build-args are missing. Exiting workflow."
+              exit 1
+          fi
+
       - name: Extract branch name
         shell: bash
         run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
-      - name: restore node cache
-        uses: actions/cache@v4
-        with:
-          path: |
-            ./node_modules
-          key: ${{ runner.os }}-nodejs-${{ matrix.env }}-${{ hashFiles('yarn.lock') }}
-      - name: restore next cache
-        uses: actions/cache@v4
-        with:
-          path: |
-            ./.next/
-            ./public
-            ./.env.local
-          key: ${{ runner.os }}-nextjs-${{ matrix.env }}-${{ github.sha }}
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
-      - name: Cache Docker layers
-        uses: actions/cache@v4
-        with:
-          path: /tmp/.buildx-cache
-          key: ${{ runner.os }}-buildx-${{ matrix.env }}-${{ hashFiles('yarn.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-buildx-${{ matrix.env }}-
-            ${{ runner.os }}-buildx-
+        id: extract_branch
 
-      - name: set aws credentials
+      - uses: actions/setup-node@v4
+        with:
+          node-version: '20.17.0'
+
+      - name: Setup npm config
+        run: |
+          echo "registry=https://registry.yarnpkg.com/" > .npmrc
+          echo "@headout:registry=https://npm.pkg.github.com" >> .npmrc
+          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
+          echo "always-auth=true" >> .npmrc
+
+      - name: Set AWS credentials
         id: set-aws-credentials
         run: |
           if [[ $APP_ENV == "production" ]]; then
@@ -126,12 +66,65 @@ jobs:
               echo "AWS_SECRET_KEY=${{ secrets.AWS_HEADOUT_TEST_SECRET_KEY }}" >> "$GITHUB_ENV"
               echo "STATIC_FILES_BUCKET=web-static-assets-test-1" >> "$GITHUB_ENV"
           fi
+
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-access-key-id: ${{ env.AWS_ACCESS_KEY }}
           aws-secret-access-key: ${{ env.AWS_SECRET_KEY }}
           aws-region: ${{ env.AWS_REGION }}
+
+      - name: Restore Node Modules
+        uses: actions/cache@v4
+        with:
+          path: ./node_modules_all
+          key: ${{ runner.os }}-nodejs-${{ hashFiles('yarn.lock') }}
+
+      - name: Install Packages
+        run: |
+          git config --global url."https://${{ github.actor }}:${{ secrets.HEADOUT_CI_PACKAGE_PAT }}@github.com/".insteadOf ssh://git@github.com/
+          if [ -d "./node_modules_all" ]; then
+            mv ./node_modules_all ./node_modules
+          fi
+          echo "Installing all dependencies"
+          yarn install --frozen-lockfile
+
+      - name: Prepare version label
+        run: |
+          echo "GIT_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
+
+      - name: Restore NEXT Build Cache for Production Environment
+        id: next-cache-prod
+        uses: actions/cache/restore@v4
+        if: matrix.env == 'production'
+        with:
+          path: |
+            ./.next/cache
+          key: ${{ runner.os }}-nextjs-${{ matrix.env }}-${{ hashFiles('yarn.lock') }}
+          restore-keys: |
+            ${{ runner.os }}-nextjs-${{ matrix.env }}-
+
+      - name: Restore NEXT Build Cache for Other Environments
+        id: next-cache-test
+        uses: actions/cache/restore@v4
+        if: matrix.env != 'production'
+        with:
+          path: |
+            ./.next/cache
+          key: ${{ runner.os }}-nextjs-${{ matrix.env }}-${{ hashFiles('yarn.lock') }}-${{ steps.extract_branch.outputs.branch }}
+          restore-keys: |
+            ${{ runner.os }}-nextjs-${{ matrix.env }}-${{ hashFiles('yarn.lock') }}-
+            ${{ runner.os }}-nextjs-${{ matrix.env }}-
+
+      - name: Build NEXT
+        run: yarn build
+        env:
+          RELEASE_VERSION: ${{ env.GIT_VERSION }}
+          NEXT_PUBLIC_HEADOUT_DOMAIN: 'https://www.headout.com'
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
       - name: Login to Amazon ECR
         id: login_ecr
         uses: aws-actions/amazon-ecr-login@v1
@@ -146,22 +139,22 @@ jobs:
             type=ref,event=branch,prefix=${{ matrix.env }}-,suffix=-{{sha}}-{{date 'YYYYMMDD'}}
             type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
 
-      - name: Validate Build Arguements
-        run: |
-          if [ -z "$APP_ENV" ] || [ -z "$WAF_API_WHITELIST_TOKEN" ]; then
-              echo "APP_ENV and/or WAF_API_WHITELIST_TOKEN build-args are missing. Exiting workflow."
-              exit 1
-          fi
-
       - name: Upload Assets to S3 🪣
         run: |
+          aws configure set default.s3.max_concurrent_requests 100
           aws s3 cp .next/static s3://$STATIC_FILES_BUCKET/mystique/_next/static --recursive
 
       - name: Warmup Assets from S3 🪣
         run: |
           node ./ci/scripts/warmup-cache.js
+        if: matrix.env == 'production'
 
-      - name: Build and push
+      - name: Prepare Node Modules required during Runtime
+        run: |
+          mv ./node_modules ./node_modules_all
+          yarn --production --frozen-lockfile
+
+      - name: Build and Push Docker Image
         id: docker_build
         uses: docker/build-push-action@v2
         with:
@@ -175,27 +168,48 @@ jobs:
             ZENDESK_API_TOKEN=${{ secrets.ZENDESK_API_TOKEN }}
             WAF_API_WHITELIST_TOKEN=${{ env.WAF_API_WHITELIST_TOKEN }}
             NEXT_PUBLIC_HEADOUT_DOMAIN=https://www.headout.com
-          cache-from: type=local,src=/tmp/.buildx-cache
-          cache-to: type=local,dest=/tmp/.buildx-cache-new
+          cache-from: type=gha,scope=${{ github.workflow }}
+          cache-to: type=gha,mode=max,scope=${{ github.workflow }}
           labels: ${{ steps.docker_meta.outputs.labels }}
-        # This ugly bit is necessary if you don't want your cache to grow forever
-        # till it hits GitHub's limit of 5GB.
-        # Temp fix
-        # https://github.com/docker/build-push-action/issues/252
-        # https://github.com/moby/buildkit/issues/1896
-      - name: Move cache
+
+      - name: Delete existing cache for Production
+        if: matrix.env == 'production' && steps.next-cache-prod.outputs.cache-hit == 'true'
         run: |
-          rm -rf /tmp/.buildx-cache
-          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
+          curl -X DELETE -H "Accept: application/vnd.github.v3+json" \
+            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+            "https://api.github.com/repos/${{ github.repository }}/actions/caches?key=${{ runner.os }}-nextjs-${{ matrix.env }}-${{ hashFiles('yarn.lock') }}"
+
+      - name: Delete existing cache for Other Environments
+        if: matrix.env != 'production' && steps.next-cache-test.outputs.cache-hit == 'true'
+        run: |
+          curl -X DELETE -H "Accept: application/vnd.github.v3+json" \
+            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+            "https://api.github.com/repos/${{ github.repository }}/actions/caches?key=${{ runner.os }}-nextjs-${{ matrix.env }}-${{ hashFiles('yarn.lock') }}-${{ steps.extract_branch.outputs.branch }}"
+
+      - name: Save NEXT Build Cache for Production Environment
+        uses: actions/cache/save@v4
+        if: matrix.env == 'production'
+        with:
+          path: |
+            ./.next/cache
+          key: ${{ runner.os }}-nextjs-${{ matrix.env }}-${{ hashFiles('yarn.lock') }}
+
+      - name: Save NEXT Build Cache for Other Environments
+        uses: actions/cache/save@v4
+        if: matrix.env != 'production'
+        with:
+          path: |
+            ./.next/cache
+          key: ${{ runner.os }}-nextjs-${{ matrix.env }}-${{ hashFiles('yarn.lock') }}-${{ steps.extract_branch.outputs.branch }}
 
   create-eb-version:
-    needs: 'push-ecr'
+    needs: 'build'
     if: startsWith(github.ref, 'refs/tags/')
     runs-on: ubuntu-latest
     env:
       AWS_EB_S3_BUCKET: ${{ secrets.AWS_EB_S3_BUCKET }}
       APP_ENV: 'production'
-      DOCKER_IMAGE_TAG: ${{ needs.push-ecr.outputs.dockerImageTag }}
+      DOCKER_IMAGE_TAG: ${{ needs.build.outputs.dockerImageTag }}
       LONG_DESCRIPTION: ${{ github.event.head_commit.message }}
     steps:
       - uses: actions/checkout@v2
@@ -206,6 +220,7 @@ jobs:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ secrets.AWS_REGION }}
+
       - name: Login to Amazon ECR
         id: login_ecr
         uses: aws-actions/amazon-ecr-login@v1
@@ -223,11 +238,13 @@ jobs:
           echo "VERSION_LABEL=$IMAGE_LABEL" >> $GITHUB_ENV
           echo "VERSION_FILE=mystique-${DOCKER_IMAGE_TAG}.zip" >> $GITHUB_ENV
           echo "VERSION_DESCRIPTION=${TRIM_DESCRIPTION:0:199}" >> $GITHUB_ENV
+
       - name: Upload package to S3 bucket
         run: |
           cat $HOME/.docker/config.json | jq -M '.auths' > .dockercfg
           aws s3 mv .dockercfg s3://$AWS_EB_S3_BUCKET/docker/.dockercfg
           aws s3 cp $VERSION_FILE s3://$AWS_EB_S3_BUCKET/mystique/$VERSION_FILE
+
       - name: Create new ElasticBeanstalk Application Version
         run: |
           aws elasticbeanstalk create-application-version \
@@ -237,12 +254,13 @@ jobs:
           --description "$VERSION_DESCRIPTION"
 
   qa-automation:
-    needs: push-ecr
+    needs: 'build'
     runs-on: ubuntu-latest
     steps:
       - name: Print Docker Image Tag
         run: |
-          echo "Docker Image Tag: ${{ needs.push-ecr.outputs.dockerImageTag }}"
+          echo "Docker Image Tag: ${{ needs.build.outputs.dockerImageTag }}"
+
       - name: Run Sanity
         run: |
           curl --location "${{ secrets.MEDUSA_TEST_URL }}/twirp/medusa.pb.qa.automation.QaAutomationService/RunTestSuite" \
@@ -250,6 +268,6 @@ jobs:
           --header 'Accept: application/json' \
           --data '{
             "commit_id": "${{ github.sha }}",
-            "tag": "${{ needs.push-ecr.outputs.dockerImageTag }}",
+            "tag": "${{ needs.build.outputs.dockerImageTag }}",
             "test_suite": "SANITY"
           }'
